(define (+ a b)
  (if (= a 0)
      b
      (inc (+ (dec a) b))))

(define (+ a b)
  (if (= a 0)
      b
      (+ (dec a) (inc b))))

#| Using the substitution model, illustrate the process generated by
each procedure in evaluating (+ 4 5). Are these processes iterative or
recursive? |#

;;; The first + function definition
;;; Illustrated with the substitution model
;;; It is a recursive process

(inc (inc (inc (inc 5))))


;;; The second + function definition
;;; The second function utilizes
;;; an iterative process

(+ 4 5)
(+ 3 6)
(+ 2 7)
(+ 1 8)
(+ 0 9)
9
